---
- name: My Test Playbook
  hosts: all
  become: true
  tasks:
  - name: Install httpd package
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"

  - name: Start Apache Service
    service:
      name: http
      state: started
    when: ansible_os_family == "RedHat"
    ignore_errors: yes

  - name: Start Apache Service
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"
    


  
